apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  containers:
  - image: luksa/fortune
    name: html-generator
    volumeMounts:
    #  名为 html 的卷挂载在容器 /var/htdocs, 可读可写
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    # 名为 html 的卷挂载在容器 /usr/share/nginx/html, 只读
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  # 名为 html 的卷, 挂载在上面两个容器中
  - name: html
    emptyDir: {}

